### ISSUE TITLE
Update documentation guide with new way for solving

### ISSUE THREAD

**Issue by neo-alex** [airbus/scikit-decide#111]
## 📚 Documentation

The new generic way to use a solver on a domain is to use a `with ...` syntax (as can be seen in the examples) - this was introduced to automatically close solvers properly, which is especially useful for some parallel C++ solvers.

However this new practice is not yet updated in the [corresponding "How to" section of the guide](https://airbus.github.io/scikit-decide/guide/#compute-a-solution).

**Comment by nhuet** [comment]
Actually the section of the guide is even wrong as `solver_with` takes normally a solver as argument and not a solver factory.
Currently the example goes:
```python
# Simple case (no arguments for domain nor solver)
solution = MyDomain.solve_with(MySolver)

# Case with solver arguments
solution = MyDomain.solve_with(lambda: MySolver(verbose=True))
```
So we definitely should update this section.

However, to be synchronized with the notebooks that keep apart for clarity the solve from the rollout, and because in real case one could need to do something with the solver outside the `with` statement, I would rather add a subsection "cleaning up the solver" where we call explicitely `_cleanup()`. Exactly as in the [maze notebook](https://github.com/airbus/scikit-decide/blob/7be4f81c96fb83ffb6315c36fc80b80106d85957/notebooks/11_maze_tuto.ipynb).
