### ISSUE TITLE
Manage notebooks in CI

### ISSUE THREAD

**Issue by galleon** [airbus/scikit-decide#121]
## 🚀 Feature
Manage notebooks in CI

## Motivation
Since the documentation rely on notebooks, they need to be tested as any other artifact

## Pitch
We need to make sure that each notebook run without any problem with the current code. Notebooks can be considered as tests and might sometimes required specific packages to run (on top of the scikit-decide library) i.e. additional test packages will have to be added to `poetry` or a `notebook-requirements.txt`

## Alternatives

None

## Additional context

- [nbmake](https://github.com/treebeardtech/nbmake)
- [post](https://semaphoreci.com/blog/test-jupyter-notebooks-with-pytest-and-nbmake)

**Comment by nhuet** [comment]
- **Locally**: To do it locally, one can install nbmake and then `pytest --nbmake notebooks/*.ipynb`.
In [nh/test_notebooks](https://github.com/nhuet/scikit-decide/tree/nh/test_notebooks), nbmake is added as dev dependency in poetry so that `poetry run pytest --nbmake notebooks/*.ipynb` works.
- **in CI**: 
   - We can do the same (install nbmake + pytest command) except we need extra dependencies to make gym nb work (ipyvirtual display, pyopengl, xvfb) --> this is done in [nh/ci_test_nb](https://github.com/nhuet/scikit-decide/tree/nh/ci_test_nb) by adding requirements files in notebooks/ folder, only for unix test to avoid complexifying dependencies to manage according to env (and on binder, it will only use unix worker). *[wip]*
   - Eventually, we could use the binder env generated (perhaps by #122) to test notebooks as the purpose is mainly to ensure that the notebooks will run on lbinder.

Note: we have to check that testing times remain reasonable, perhaps by specifying a timeout by cell. Nbmake allows that but generates an error when timeout is reached. We can also tell it to not raise errors but then we miss the purpose of testing notebooks... So light versions of notebooks are needed, perhaps by parametriziing them using [papermill ](https://papermill.readthedocs.io/en/latest/)

**Comment by g-poveda** [comment]
Decision : we want to focus more on the implementation of more unit test.
