### ISSUE TITLE
Rollout for RLDomain

### ISSUE THREAD

**Issue by g-poveda** [airbus/scikit-decide#360]
I implemented a pure RLDomain
and just want to run a rollout from it (given an initial state given as input)
however the "domain.set_memory(from_memory)" fails because there is no set_memory for Environment domains such as RL ones, what would be the right way to circumvent this ?

**Comment by neo-alex** [comment]
Hello,
The ususal assumption in RL is that you are **not** necessarily able to initialize the environment from a given state (like in real life) - only an argument-free reset() is generally provided. In your case, you could maybe create a custom Domain inheriting from [Simulation](https://github.com/airbus/scikit-decide/blob/8a139bebcdeb1cd037015fc1f791971364fc2dfd/skdecide/builders/domain/dynamics.py#L137) (which has a `set_memory(...)` method) rather than [Environment](https://github.com/airbus/scikit-decide/blob/8a139bebcdeb1cd037015fc1f791971364fc2dfd/skdecide/builders/domain/dynamics.py#L30) (the one used generally for RL) for the dynamics characteristic.
Does that work out for you?

**Comment by g-poveda** [comment]
Yes thank you
