### ISSUE TITLE
v1.0.1 imports discrete-optimization in solvers.py although discrete-optimization is not a mandatory dependency

### ISSUE THREAD

**Issue by NansDarraillan** [airbus/scikit-decide#423]
## 🐛 Bug

v1.0.1 imports discrete-optimization in solvers.py although discrete-optimization is not a mandatory dependency

## To Reproduce

install scikit-decide 1.0.1 without any option 
import skdecide

ModuleNotFoundError: No module named 'discrete_optimization'

## Expected behavior

Please keep discrete-optimization as an optional dependency (it simplifies a lot the installation of skdecide)

## Environment

python 3.11

**Comment by nhuet** [comment]
Hi. discrete-optimization is now a mandatory dependency, used to define hyperparameters of solvers in order to be able to tune them easily with optuna (there is an example in the tutorials for ICAPS 2024, more precisely in the [scheduling tutorial](https://github.com/fteicht/icaps24-skdecide-tutorial/blob/main/notebooks/icaps24_skdecide_tutorial_scheduling.ipynb)). 

It was a mistake that the requirement was still optional in 1.0.1 and has been corrected starting from 1.0.2.

However this should be imperceptible for you now as the last versions of discrete-optimization does not require the installation of minizinc anymore (which was perhaps the part that complexified the installation process for you).

**Comment by NansDarraillan** [comment]
Hi, thanks, checked an worked with scikit-decide 1.0.2
